# Generated by Django 5.2.4 on 2025-09-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_noticia_destaque_categoria_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='noticia-sem-slug', unique=True),
        ),
    ]
