# Generated by Django 5.2.4 on 2025-09-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
    ]
