# Generated by Django 5.2.4 on 2026-05-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_remove_noticia_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='Redação', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='noticias.categoria'),
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('cliente', 'Morador / Cliente'), ('loja', 'Loja / Comércio')], default='cliente', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='contribuicoes/')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando revisão'), ('aprovado', 'Publicado'), ('rejeitado', 'Não aprovado')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.categoria')),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
                'ordering': ['-data_envio'],
            },
        ),
    ]
