# Generated by Django 5.2.4 on 2026-05-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_anuncio_contribuicao_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribuicao',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Envio aguardando análise', 'verbose_name_plural': 'Envios da comunidade (analisar aqui)'},
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.categoria', verbose_name='Categoria sugerida'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='conteudo',
            field=models.TextField(verbose_name='Texto completo'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do envio'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome ou loja'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Morador / Cliente'), ('loja', 'Loja / Comércio')], default='cliente', max_length=20, verbose_name='Quem enviou'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar no site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('morador', 'Morador'), ('loja', 'Loja / Comércio'), ('assinante', 'Assinante / Parceiro')], default='morador', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('is_assinante', models.BooleanField(default=False, help_text='Acesso a conteúdos exclusivos e parcerias fechadas.')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuário',
                'verbose_name_plural': 'Perfis de usuários',
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'unique_together': {('noticia', 'usuario')},
            },
        ),
    ]
