# Generated by Django 5.2.4 on 2026-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_alter_contribuicao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicao',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 ou WebM, até 50 MB.', null=True, upload_to='contribuicoes/videos/', verbose_name='Vídeo (opcional)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='exclusivo_assinantes',
            field=models.BooleanField(default=False, help_text='Somente usuários assinantes / parceiros podem ver o conteúdo completo.'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo da notícia (MP4, WebM).', null=True, upload_to='noticias/videos/'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Morador / Cliente'), ('loja', 'Loja / Comércio'), ('empresa', 'Empresa parceira')], default='cliente', max_length=20, verbose_name='Quem enviou'),
        ),
    ]
