# Generated by Django 5.2.4 on 2026-08-29 16:09

import django.db.models.deletion
import noticias.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_contribuicao_video_noticia_exclusivo_assinantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='slot',
            field=models.CharField(choices=[('top', 'Banner topo (abaixo do menu)'), ('sidebar', 'Barra lateral (desktop)'), ('article', 'Dentro da notícia'), ('feed', 'Entre notícias (lista)'), ('mobile', 'Entre conteúdos no celular')], max_length=20, unique=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=noticias.image_utils.upload_path_contrib),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto principal (capa) da notícia.', null=True, upload_to='noticias/'),
        ),
        migrations.CreateModel(
            name='ContribuicaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=noticias.image_utils.upload_path_contrib_galeria)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('contribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='noticias.contribuicao')),
            ],
            options={
                'verbose_name': 'Foto do envio',
                'verbose_name_plural': 'Fotos dos envios',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=noticias.image_utils.upload_path_galeria)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='noticias.noticia')),
            ],
            options={
                'verbose_name': 'Foto da notícia',
                'verbose_name_plural': 'Fotos da notícia (galeria)',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
