# Generated by Django 5.2.4 on 2026-09-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_alter_anuncio_slot_alter_contribuicao_imagem_and_more'),
        ('plataforma', '0001_portal_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='anuncio',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='plataforma.portal'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='plataforma.portal'),
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes', to='plataforma.portal'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='plataforma.portal'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='slot',
            field=models.CharField(choices=[('top', 'Banner topo (abaixo do menu)'), ('sidebar', 'Barra lateral (desktop)'), ('article', 'Dentro da notícia'), ('feed', 'Entre notícias (lista)'), ('mobile', 'Entre conteúdos no celular')], max_length=20, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddIndex(
            model_name='contribuicao',
            index=models.Index(fields=['portal', 'status', '-data_envio'], name='noticias_co_portal__d91136_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['portal', '-data_publicacao'], name='noticias_no_portal__29a9d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='anuncio',
            constraint=models.UniqueConstraint(fields=('portal', 'slot'), name='uniq_anuncio_portal_slot'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('portal', 'slug'), name='uniq_categoria_portal_slug'),
        ),
    ]
