# Generated by Django 5.2.4 on 2026-09-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_portal_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
