# Generated by Django 5.2.4 on 2026-09-14 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('max_storage_mb', models.PositiveIntegerField(default=1024)),
                ('max_usuarios', models.PositiveIntegerField(default=5)),
                ('max_noticias_mes', models.PositiveIntegerField(blank=True, help_text='Vazio = sem limite mensal.', null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Subdomínio: {slug}.plataforma.com.br', unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Domínio próprio futuro, ex.: www.noticiascliente.com.br', max_length=255)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(help_text='UF ou nome do estado', max_length=50)),
                ('regiao', models.CharField(blank=True, max_length=120)),
                ('slogan', models.CharField(blank=True, max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], db_index=True, default='ativo', max_length=20)),
                ('pagamento_status', models.CharField(choices=[('cortesia', 'Cortesia / legado'), ('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], default='cortesia', max_length=20)),
                ('cliente_nome', models.CharField(blank=True, max_length=120)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso_em', models.DateTimeField(blank=True, null=True)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portais', to='plataforma.plano')),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('autor', 'Autor / redator'), ('moderador', 'Moderador')], default='admin', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='plataforma.portal')),
            ],
            options={
                'verbose_name': 'Equipe do portal',
                'verbose_name_plural': 'Equipes dos portais',
            },
        ),
        migrations.AddIndex(
            model_name='portal',
            index=models.Index(fields=['status', 'slug'], name='plataforma__status_4e46e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('usuario', 'portal'), name='uniq_membership_usuario_portal'),
        ),
    ]
