# Generated by Django 5.2.4 on 2026-09-15 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('onboarding', 'Onboarding'), ('recuperacao_senha', 'Recuperação de senha'), ('teste_smtp', 'Teste SMTP'), ('reenvio_acesso', 'Reenvio de acesso'), ('notificacao_admin', 'Notificação administrativa')], db_index=True, max_length=40)),
                ('destinatario', models.EmailField(db_index=True, max_length=254)),
                ('assunto', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou'), ('nao_configurado', 'Não configurado')], db_index=True, default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('tentativas', models.PositiveIntegerField(default=1)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='plataforma.cliente')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='plataforma.portal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_plataforma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de e-mail',
                'verbose_name_plural': 'Logs de e-mail',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['destinatario', 'status'], name='plataforma__destina_193f71_idx'), models.Index(fields=['tipo', 'status'], name='plataforma__tipo_6a2379_idx')],
            },
        ),
    ]
