# Generated by Django 5.2.4 on 2026-09-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_portal_setup_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='setup_concluido',
            field=models.BooleanField(default=False, help_text='False = portal novo ainda sem nome/slug definitivos (wizard futuro). Portais já existentes na migration ficam True.'),
        ),
    ]
