# Generated by Django 5.1.6 on 2026-09-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_analytics_funil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('duvida', 'Dúvida'), ('problema', 'Problema'), ('sugestao', 'Sugestão')], default='duvida', max_length=20)),
                ('assunto', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('aguardando_cliente', 'Aguardando cliente'), ('aguardando_suporte', 'Aguardando suporte'), ('encerrada', 'Encerrada')], db_index=True, default='aguardando_suporte', max_length=24)),
                ('ultima_mensagem', models.CharField(blank=True, max_length=180)),
                ('nao_lidas_cliente', models.PositiveIntegerField(default=0)),
                ('nao_lidas_master', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_index=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversa de ajuda',
                'verbose_name_plural': 'Conversas de ajuda',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('suporte', 'Suporte')], max_length=16)),
                ('texto', models.TextField(max_length=4000)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensagem de ajuda',
                'verbose_name_plural': 'Mensagens de ajuda',
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversaajuda',
            name='aberto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_ajuda_abertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversaajuda',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ajuda', to='plataforma.portal'),
        ),
        migrations.AddField(
            model_name='mensagemajuda',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_ajuda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemajuda',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='plataforma.conversaajuda'),
        ),
        migrations.AddIndex(
            model_name='conversaajuda',
            index=models.Index(fields=['portal', '-atualizado_em'], name='plataforma__portal__9652c0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversaajuda',
            index=models.Index(fields=['status', '-atualizado_em'], name='plataforma__status_5eb3a6_idx'),
        ),
    ]
